version: '3.8'
services:
  xtls-reality:
    image: xtls-reality:latest
    build: .
    environment:
      - SNI=images.apple.com
    container_name: xtls-reality
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./config:/opt/xray/config
